name: Update Daily Log

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

permissions:
  contents: write

jobs:
  update-log:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Run update script
      run: |
        python update_log.py

    - name: Commit and push changes
      run: |
        git config --global user.name "sssonu"
        git config --global user.email "sonu23645@gmail.com"
        git add daily_log.txt
        git commit -m "Automated update: $(date -u +"%Y-%m-%d %H:%M:%S")"
        git push
